using System;
using System.Collections.Generic;

namespace FriendOverlay.Core
{
    /// <summary>Embedded five-locale UI string tables for FriendOverlay.</summary>
    public static class UiCatalog
    {
        private static readonly Dictionary<string, string> Zh = BuildZh();
        private static readonly Dictionary<string, string> En = BuildEn();
        private static readonly Dictionary<string, string> Ru = BuildRu();
        private static readonly Dictionary<string, string> Ja = BuildJa();
        private static readonly Dictionary<string, string> De = BuildDe();

        public static IEnumerable<string> AllKeys => En.Keys;

        public static string T(string key) => Lookup(LanguageResolver.Current, key);

        public static string Tf(string key, params object[] args)
        {
            var format = T(key);
            try
            {
                return string.Format(format, args);
            }
            catch (FormatException)
            {
                return format;
            }
        }

        public static string Lookup(string languageCode, string key)
        {
            if (string.IsNullOrEmpty(key))
                return string.Empty;

            var table = TableFor(languageCode);
            if (table != null && table.TryGetValue(key, out var hit) && !string.IsNullOrEmpty(hit))
                return hit;

            if (!string.Equals(languageCode, "en", StringComparison.Ordinal)
                && En.TryGetValue(key, out var en) && !string.IsNullOrEmpty(en))
                return en;

            return key;
        }

        private static Dictionary<string, string>? TableFor(string code) => code switch
        {
            "zh-CN" => Zh,
            "en" => En,
            "ru" => Ru,
            "ja" => Ja,
            "de" => De,
            _ => null,
        };

        private static Dictionary<string, string> BuildZh() => new Dictionary<string, string>
        {
            ["tab.following"] = "关注",
            ["tab.followers"] = "关注我的人",
            ["btn.close"] = "关闭",
            ["btn.native"] = "原生面板",
            ["btn.refresh"] = "刷新",
            ["btn.cancel"] = "取消",
            ["btn.confirm"] = "确认",
            ["btn.join"] = "加入",
            ["btn.watch"] = "观战",
            ["btn.chat"] = "私聊",
            ["btn.invite"] = "邀请",
            ["btn.inviting"] = "邀请中",
            ["btn.invited"] = "已邀请",
            ["btn.follow_back"] = "回关",
            ["btn.mutual"] = "⇌ 已互关",
            ["menu.pin"] = "置顶",
            ["menu.unpin"] = "取消置顶",
            ["menu.pin_full"] = "置顶（已满 {0}）",
            ["menu.unfollow"] = "取消关注",
            ["menu.blacklist"] = "加入黑名单",
            ["search.placeholder"] = "输入名称或 ID…",
            ["filter.all"] = "全部",
            ["filter.online"] = "在线",
            ["filter.busy"] = "忙碌",
            ["filter.mutual"] = "互关",
            ["filter.offline"] = "离线",
            ["section.pinned"] = "置顶",
            ["section.joinable"] = "在线 · 可加入",
            ["section.busy"] = "在线 · 对战中",
            ["section.offline"] = "离线",
            ["sort.prefix"] = "排序 · {0}",
            ["sort.name"] = "名称 A-Z",
            ["sort.rank"] = "战力 ↓",
            ["sort.forecast"] = "洞察 ↓",
            ["sort.status"] = "状态",
            ["count.loaded"] = "已加载 {0}",
            ["count.following"] = "已关注 {0}",
            ["status.ready"] = "准备中",
            ["status.syncing"] = "同步中",
            ["status.syncing_n"] = "同步中 {0}/{1}",
            ["status.synced_n"] = "已同步 {0}/{1}",
            ["status.loaded_unknown"] = "已加载 {0} · 状态未知",
            ["status.showing"] = "显示 {0} / {1}",
            ["status.unknown"] = "状态未知",
            ["status.state_n"] = "状态{0}",
            ["empty.loading_following"] = "正在拉取关注列表…",
            ["empty.loading_followers"] = "正在拉取关注我的人…",
            ["empty.no_friends"] = "没有符合条件的好友",
            ["empty.no_players"] = "没有符合条件的玩家",
            ["launcher.open"] = "打开叠加面板  ·  {0}",
            ["footer.help"] = "拖动标题栏移动  ·  边框单向缩放 / 四角整体缩放  ·  ⋯/右键 更多操作  ·  邀请可选战斗类型  ·  {0} 原生面板  ·  Ctrl+F 搜索  ·  R 刷新  ·  Esc 关闭菜单",
            ["footer.letters"] = "  ·  Ctrl+L 字母模式（诊断）",
            ["confirm.unfollow_title"] = "取消关注",
            ["confirm.unfollow_body"] = "确认取消关注 {0} ？",
            ["confirm.blacklist_title"] = "加入黑名单",
            ["confirm.blacklist_body"] = "确认拉黑 {0} ？",
            ["picker.title"] = "邀请 {0} 参与",
            ["picker.unavailable"] = "{0}（暂未开放）",
            ["battle.vs1v1"] = "1对1",
            ["battle.vs2v2"] = "2对2",
            ["battle.survive"] = "生存模式",
            ["battle.team"] = "组队匹配",
            ["battle.scuffle4"] = "4人混战",
            ["battle.rift1v1"] = "时空裂隙 1V1",
            ["battle.rift2v2"] = "时空裂隙 2V2",
            ["state.idle"] = "空闲",
            ["state.1v1"] = "1V1对战",
            ["state.2v2"] = "2V2对战",
            ["state.survive"] = "生存战",
            ["state.survive2v2"] = "生存2V2",
            ["state.scuffle4"] = "4人混战",
            ["state.rift"] = "时空裂隙",
            ["state.rift2"] = "时空裂隙2",
            ["state.level"] = "关卡",
            ["state.guider"] = "指挥学院",
            ["state.watch"] = "观战中",
            ["state.custom"] = "自定义房间",
            ["state.comp_battle"] = "比赛中",
            ["state.comp_idle"] = "等待比赛中",
            ["state.offline"] = "离线",
        };

        private static Dictionary<string, string> BuildEn() => new Dictionary<string, string>
        {
            ["tab.following"] = "Following",
            ["tab.followers"] = "Followers",
            ["btn.close"] = "Close",
            ["btn.native"] = "Native",
            ["btn.refresh"] = "Refresh",
            ["btn.cancel"] = "Cancel",
            ["btn.confirm"] = "OK",
            ["btn.join"] = "Join",
            ["btn.watch"] = "Spectate",
            ["btn.chat"] = "Chat",
            ["btn.invite"] = "Invite",
            ["btn.inviting"] = "Inviting",
            ["btn.invited"] = "Invited",
            ["btn.follow_back"] = "Follow",
            ["btn.mutual"] = "⇌ Mutual",
            ["menu.pin"] = "Pin",
            ["menu.unpin"] = "Unpin",
            ["menu.pin_full"] = "Pin (full {0})",
            ["menu.unfollow"] = "Unfollow",
            ["menu.blacklist"] = "Blacklist",
            ["search.placeholder"] = "Name or ID…",
            ["filter.all"] = "All",
            ["filter.online"] = "Online",
            ["filter.busy"] = "Busy",
            ["filter.mutual"] = "Mutual",
            ["filter.offline"] = "Offline",
            ["section.pinned"] = "Pinned",
            ["section.joinable"] = "Online · Joinable",
            ["section.busy"] = "Online · In battle",
            ["section.offline"] = "Offline",
            ["sort.prefix"] = "Sort · {0}",
            ["sort.name"] = "Name A-Z",
            ["sort.rank"] = "Power ↓",
            ["sort.forecast"] = "Insight ↓",
            ["sort.status"] = "Status",
            ["count.loaded"] = "Loaded {0}",
            ["count.following"] = "Following {0}",
            ["status.ready"] = "Ready",
            ["status.syncing"] = "Syncing",
            ["status.syncing_n"] = "Syncing {0}/{1}",
            ["status.synced_n"] = "Synced {0}/{1}",
            ["status.loaded_unknown"] = "Loaded {0} · status unknown",
            ["status.showing"] = "Showing {0} / {1}",
            ["status.unknown"] = "Unknown",
            ["status.state_n"] = "State {0}",
            ["empty.loading_following"] = "Loading following…",
            ["empty.loading_followers"] = "Loading followers…",
            ["empty.no_friends"] = "No matching friends",
            ["empty.no_players"] = "No matching players",
            ["launcher.open"] = "Open overlay  ·  {0}",
            ["footer.help"] = "Drag title  ·  Resize edges/corners  ·  ⋯/RMB more  ·  Invite picks battle  ·  {0} native  ·  Ctrl+F search  ·  R refresh  ·  Esc close menu",
            ["footer.letters"] = "  ·  Ctrl+L letter mode (diag)",
            ["confirm.unfollow_title"] = "Unfollow",
            ["confirm.unfollow_body"] = "Unfollow {0}?",
            ["confirm.blacklist_title"] = "Blacklist",
            ["confirm.blacklist_body"] = "Blacklist {0}?",
            ["picker.title"] = "Invite {0}",
            ["picker.unavailable"] = "{0} (unavailable)",
            ["battle.vs1v1"] = "1v1",
            ["battle.vs2v2"] = "2v2",
            ["battle.survive"] = "Survival",
            ["battle.team"] = "Team match",
            ["battle.scuffle4"] = "4-player scuffle",
            ["battle.rift1v1"] = "Rift 1v1",
            ["battle.rift2v2"] = "Rift 2v2",
            ["state.idle"] = "Idle",
            ["state.1v1"] = "1v1",
            ["state.2v2"] = "2v2",
            ["state.survive"] = "Survival",
            ["state.survive2v2"] = "Survival 2v2",
            ["state.scuffle4"] = "4-player scuffle",
            ["state.rift"] = "Dimensional Rift",
            ["state.rift2"] = "Dimensional Rift 2",
            ["state.level"] = "Mission",
            ["state.guider"] = "Command Academy",
            ["state.watch"] = "Spectating",
            ["state.custom"] = "Custom room",
            ["state.comp_battle"] = "In match",
            ["state.comp_idle"] = "Waiting for match",
            ["state.offline"] = "Offline",
        };

        private static Dictionary<string, string> BuildRu() => new Dictionary<string, string>
        {
            ["tab.following"] = "Подписки",
            ["tab.followers"] = "Подписчики",
            ["btn.close"] = "Закрыть",
            ["btn.native"] = "Обычная",
            ["btn.refresh"] = "Обновить",
            ["btn.cancel"] = "Отмена",
            ["btn.confirm"] = "ОК",
            ["btn.join"] = "Войти",
            ["btn.watch"] = "Смотреть",
            ["btn.chat"] = "Чат",
            ["btn.invite"] = "Пригласить",
            ["btn.inviting"] = "Приглашение",
            ["btn.invited"] = "Приглашён",
            ["btn.follow_back"] = "Подписаться",
            ["btn.mutual"] = "⇌ Взаимно",
            ["menu.pin"] = "Закрепить",
            ["menu.unpin"] = "Открепить",
            ["menu.pin_full"] = "Закрепить (лимит {0})",
            ["menu.unfollow"] = "Отписаться",
            ["menu.blacklist"] = "В ЧС",
            ["search.placeholder"] = "Имя или ID…",
            ["filter.all"] = "Все",
            ["filter.online"] = "В сети",
            ["filter.busy"] = "Занят",
            ["filter.mutual"] = "Взаим.",
            ["filter.offline"] = "Не в сети",
            ["section.pinned"] = "Закреплённые",
            ["section.joinable"] = "В сети · можно войти",
            ["section.busy"] = "В сети · в бою",
            ["section.offline"] = "Не в сети",
            ["sort.prefix"] = "Сорт. · {0}",
            ["sort.name"] = "Имя A-Z",
            ["sort.rank"] = "Сила ↓",
            ["sort.forecast"] = "Инсайт ↓",
            ["sort.status"] = "Статус",
            ["count.loaded"] = "Загружено {0}",
            ["count.following"] = "Подписок {0}",
            ["status.ready"] = "Готово",
            ["status.syncing"] = "Синхронизация",
            ["status.syncing_n"] = "Синхр. {0}/{1}",
            ["status.synced_n"] = "Синхр. готово {0}/{1}",
            ["status.loaded_unknown"] = "Загружено {0} · статус неизвестен",
            ["status.showing"] = "Показано {0} / {1}",
            ["status.unknown"] = "Неизвестно",
            ["status.state_n"] = "Статус {0}",
            ["empty.loading_following"] = "Загрузка подписок…",
            ["empty.loading_followers"] = "Загрузка подписчиков…",
            ["empty.no_friends"] = "Нет подходящих друзей",
            ["empty.no_players"] = "Нет подходящих игроков",
            ["launcher.open"] = "Открыть оверлей  ·  {0}",
            ["footer.help"] = "Тяните заголовок  ·  Масштаб краёв/углов  ·  ⋯/ПКМ ещё  ·  Приглашение с типом боя  ·  {0} обычная  ·  Ctrl+F поиск  ·  R обновить  ·  Esc меню",
            ["footer.letters"] = "  ·  Ctrl+L буквы (диаг.)",
            ["confirm.unfollow_title"] = "Отписаться",
            ["confirm.unfollow_body"] = "Отписаться от {0}?",
            ["confirm.blacklist_title"] = "В чёрный список",
            ["confirm.blacklist_body"] = "Добавить {0} в ЧС?",
            ["picker.title"] = "Пригласить {0}",
            ["picker.unavailable"] = "{0} (недоступно)",
            ["battle.vs1v1"] = "1 на 1",
            ["battle.vs2v2"] = "2 на 2",
            ["battle.survive"] = "Выживание",
            ["battle.team"] = "Командный матч",
            ["battle.scuffle4"] = "Схватка 4",
            ["battle.rift1v1"] = "Разлом 1v1",
            ["battle.rift2v2"] = "Разлом 2v2",
            ["state.idle"] = "Свободен",
            ["state.1v1"] = "Бой 1v1",
            ["state.2v2"] = "Бой 2v2",
            ["state.survive"] = "Выживание",
            ["state.survive2v2"] = "Выживание 2v2",
            ["state.scuffle4"] = "Схватка 4",
            ["state.rift"] = "Разлом",
            ["state.rift2"] = "Разлом 2",
            ["state.level"] = "Миссия",
            ["state.guider"] = "Академия",
            ["state.watch"] = "Наблюдает",
            ["state.custom"] = "Своя комната",
            ["state.comp_battle"] = "В матче",
            ["state.comp_idle"] = "Ждёт матч",
            ["state.offline"] = "Не в сети",
        };

        private static Dictionary<string, string> BuildJa() => new Dictionary<string, string>
        {
            ["tab.following"] = "フォロー",
            ["tab.followers"] = "フォロワー",
            ["btn.close"] = "閉じる",
            ["btn.native"] = "標準UI",
            ["btn.refresh"] = "更新",
            ["btn.cancel"] = "キャンセル",
            ["btn.confirm"] = "OK",
            ["btn.join"] = "参加",
            ["btn.watch"] = "観戦",
            ["btn.chat"] = "チャット",
            ["btn.invite"] = "招待",
            ["btn.inviting"] = "招待中",
            ["btn.invited"] = "招待済",
            ["btn.follow_back"] = "フォロー",
            ["btn.mutual"] = "⇌ 相互",
            ["menu.pin"] = "ピン留め",
            ["menu.unpin"] = "ピン解除",
            ["menu.pin_full"] = "ピン留め（上限 {0}）",
            ["menu.unfollow"] = "フォロー解除",
            ["menu.blacklist"] = "ブロック",
            ["search.placeholder"] = "名前または ID…",
            ["filter.all"] = "すべて",
            ["filter.online"] = "オンライン",
            ["filter.busy"] = "対戦中",
            ["filter.mutual"] = "相互",
            ["filter.offline"] = "オフライン",
            ["section.pinned"] = "ピン留め",
            ["section.joinable"] = "オンライン · 参加可",
            ["section.busy"] = "オンライン · 対戦中",
            ["section.offline"] = "オフライン",
            ["sort.prefix"] = "並び · {0}",
            ["sort.name"] = "名前 A-Z",
            ["sort.rank"] = "戦力 ↓",
            ["sort.forecast"] = "洞察 ↓",
            ["sort.status"] = "状態",
            ["count.loaded"] = "読込 {0}",
            ["count.following"] = "フォロー {0}",
            ["status.ready"] = "準備中",
            ["status.syncing"] = "同期中",
            ["status.syncing_n"] = "同期中 {0}/{1}",
            ["status.synced_n"] = "同期済 {0}/{1}",
            ["status.loaded_unknown"] = "読込 {0} · 状態不明",
            ["status.showing"] = "表示 {0} / {1}",
            ["status.unknown"] = "不明",
            ["status.state_n"] = "状態{0}",
            ["empty.loading_following"] = "フォロー一覧を取得中…",
            ["empty.loading_followers"] = "フォロワーを取得中…",
            ["empty.no_friends"] = "条件に合うフレンドなし",
            ["empty.no_players"] = "条件に合うプレイヤーなし",
            ["launcher.open"] = "オーバーレイを開く  ·  {0}",
            ["footer.help"] = "タイトルをドラッグ  ·  辺/角でリサイズ  ·  ⋯/右クリックで操作  ·  招待で戦闘タイプ選択  ·  {0} 標準UI  ·  Ctrl+F 検索  ·  R 更新  ·  Esc メニュー閉",
            ["footer.letters"] = "  ·  Ctrl+L 文字モード（診断）",
            ["confirm.unfollow_title"] = "フォロー解除",
            ["confirm.unfollow_body"] = "{0} のフォローを解除しますか？",
            ["confirm.blacklist_title"] = "ブロック",
            ["confirm.blacklist_body"] = "{0} をブロックしますか？",
            ["picker.title"] = "{0} を招待",
            ["picker.unavailable"] = "{0}（未開放）",
            ["battle.vs1v1"] = "1対1",
            ["battle.vs2v2"] = "2対2",
            ["battle.survive"] = "サバイバル",
            ["battle.team"] = "チームマッチ",
            ["battle.scuffle4"] = "4人乱闘",
            ["battle.rift1v1"] = "時空の裂け目 1V1",
            ["battle.rift2v2"] = "時空の裂け目 2V2",
            ["state.idle"] = "待機",
            ["state.1v1"] = "1V1対戦",
            ["state.2v2"] = "2V2対戦",
            ["state.survive"] = "サバイバル",
            ["state.survive2v2"] = "サバイバル2V2",
            ["state.scuffle4"] = "4人乱闘",
            ["state.rift"] = "時空の裂け目",
            ["state.rift2"] = "時空の裂け目2",
            ["state.level"] = "ミッション",
            ["state.guider"] = "指揮学院",
            ["state.watch"] = "観戦中",
            ["state.custom"] = "カスタム部屋",
            ["state.comp_battle"] = "試合中",
            ["state.comp_idle"] = "試合待ち",
            ["state.offline"] = "オフライン",
        };

        private static Dictionary<string, string> BuildDe() => new Dictionary<string, string>
        {
            ["tab.following"] = "Folge ich",
            ["tab.followers"] = "Follower",
            ["btn.close"] = "Schließen",
            ["btn.native"] = "Nativ",
            ["btn.refresh"] = "Aktual.",
            ["btn.cancel"] = "Abbrechen",
            ["btn.confirm"] = "OK",
            ["btn.join"] = "Beitreten",
            ["btn.watch"] = "Zuschauen",
            ["btn.chat"] = "Chat",
            ["btn.invite"] = "Einladen",
            ["btn.inviting"] = "Einladen…",
            ["btn.invited"] = "Eingeladen",
            ["btn.follow_back"] = "Folgen",
            ["btn.mutual"] = "⇌ Gegenseitig",
            ["menu.pin"] = "Anheften",
            ["menu.unpin"] = "Loslösen",
            ["menu.pin_full"] = "Anheften (voll {0})",
            ["menu.unfollow"] = "Entfolgen",
            ["menu.blacklist"] = "Sperren",
            ["search.placeholder"] = "Name oder ID…",
            ["filter.all"] = "Alle",
            ["filter.online"] = "Online",
            ["filter.busy"] = "Beschäftigt",
            ["filter.mutual"] = "Gegens.",
            ["filter.offline"] = "Offline",
            ["section.pinned"] = "Angepinnt",
            ["section.joinable"] = "Online · Beitritt möglich",
            ["section.busy"] = "Online · Im Kampf",
            ["section.offline"] = "Offline",
            ["sort.prefix"] = "Sort. · {0}",
            ["sort.name"] = "Name A-Z",
            ["sort.rank"] = "Stärke ↓",
            ["sort.forecast"] = "Einblick ↓",
            ["sort.status"] = "Status",
            ["count.loaded"] = "Geladen {0}",
            ["count.following"] = "Folge {0}",
            ["status.ready"] = "Bereit",
            ["status.syncing"] = "Sync…",
            ["status.syncing_n"] = "Sync {0}/{1}",
            ["status.synced_n"] = "Synced {0}/{1}",
            ["status.loaded_unknown"] = "Geladen {0} · Status unbekannt",
            ["status.showing"] = "Anzeige {0} / {1}",
            ["status.unknown"] = "Unbekannt",
            ["status.state_n"] = "Status {0}",
            ["empty.loading_following"] = "Folge-Liste wird geladen…",
            ["empty.loading_followers"] = "Follower werden geladen…",
            ["empty.no_friends"] = "Keine passenden Freunde",
            ["empty.no_players"] = "Keine passenden Spieler",
            ["launcher.open"] = "Overlay öffnen  ·  {0}",
            ["footer.help"] = "Titel ziehen  ·  Ränder/Ecken skalieren  ·  ⋯/RMB mehr  ·  Einladung wählt Kampfart  ·  {0} nativ  ·  Ctrl+F Suche  ·  R Aktual.  ·  Esc Menü",
            ["footer.letters"] = "  ·  Ctrl+L Buchstaben (Diag.)",
            ["confirm.unfollow_title"] = "Entfolgen",
            ["confirm.unfollow_body"] = "{0} entfolgen?",
            ["confirm.blacklist_title"] = "Sperren",
            ["confirm.blacklist_body"] = "{0} sperren?",
            ["picker.title"] = "{0} einladen",
            ["picker.unavailable"] = "{0} (nicht verfügbar)",
            ["battle.vs1v1"] = "1 gegen 1",
            ["battle.vs2v2"] = "2 gegen 2",
            ["battle.survive"] = "Überleben",
            ["battle.team"] = "Team-Match",
            ["battle.scuffle4"] = "4er-Gemenge",
            ["battle.rift1v1"] = "Riss 1V1",
            ["battle.rift2v2"] = "Riss 2V2",
            ["state.idle"] = "Idle",
            ["state.1v1"] = "1V1-Kampf",
            ["state.2v2"] = "2V2-Kampf",
            ["state.survive"] = "Überleben",
            ["state.survive2v2"] = "Überleben 2V2",
            ["state.scuffle4"] = "4er-Gemenge",
            ["state.rift"] = "Dimensionsriss",
            ["state.rift2"] = "Dimensionsriss 2",
            ["state.level"] = "Mission",
            ["state.guider"] = "Kommando-Akademie",
            ["state.watch"] = "Zuschauen",
            ["state.custom"] = "Custom-Raum",
            ["state.comp_battle"] = "Im Match",
            ["state.comp_idle"] = "Wartet auf Match",
            ["state.offline"] = "Offline",
        };
    }
}
